version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend.DockerFile
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ".:/app"
    entrypoint: /app/backend_entrypoint.sh
    env_file:
      - .env.local
    depends_on:
      - pg_db
    links:
      - pg_db
    stdin_open: true
  
  pg_db:
    image: postgres:latest
    restart: always
    env_file:
      - .env.local
    volumes:
      - "marshal_pg_db:/var/lib/postgresql/data"
  
volumes:
  marshal_pg_db:
    

  

