version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend.DockerFile
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.local
    depends_on:
      - pg_db
    links:
      - pg_db
  
  pg_db:
    image: postgres:latest
    restart: always
    env_file:
      - .env.local
    volumes:
      - "marshal_pg_db:/var/lib/postgresql/data"
  
volumes:
  marshal_pg_db:
    

  

