# Generated by Django 4.2.1 on 2023-07-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('title', models.CharField(help_text='Title of the app', max_length=255, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, upload_to='pass_vault/app/')),
                ('type', models.CharField(choices=[('WEB', 'Web'), ('MBE', 'Mobile'), ('DTP', 'Desktop')], default='WEB', max_length=3)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
