# Generated by Django 4.2.1 on 2024-10-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_vault', '0003_add_password_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='password',
            unique_together={('app', 'password')},
        ),
    ]
